### ISSUE TITLE
xpath + END_ELEMENT

### ISSUE THREAD

**Issue by sevkin** [dkrnl/SimpleXMLReader#1]
```
$this->registerCallback("/КоммерческаяИнформация/Каталог", array($this, "callbackCatalogEnd"), XMLREADER::END_ELEMENT);
```

вызывается, но курсор стоит на последнем элементе внутри ожидаемого

```
$this->registerCallback("/КоммерческаяИнформация/ПакетПредложений", array($this, "callbackOffersListEnd"), XMLREADER::END_ELEMENT);
```

вообще не вызывается. вот на этом семпле http://pastebin.com/UcWAaPYs

**Comment by distvan** [comment]
I have one question.
How do you registrer a callback to an Xml element by xpath?

For example:
<root>
<items>
 <item></item>
  <item></item>
</items>
</root>
/root/items/item, SimpleXmlReader::END_ELEMENT

$this->registerCallback("/root/items/item", array($this, "callbackEndItem"), XMLREADER::END_ELEMENT);

I think it will missed.

Maybe take a look at public function currentXpath and replace the switch case with if else and put a line:  in_array($this->nodesType[$depth], array(self::ELEMENT, self::END_ELEMENT))
