### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by standus** [dkrnl/SimpleXMLReader#6]
Hi,
I tested your code and see that
$this->xml = $reader->expandSimpleXml();
delete some code.
From this:
<CONTACT title="tttttt" first="nnnnn" last="llllll" phone="222222" email="eeee">aaaaaaaaaaa</CONTACT>
When I dump it I got in array only: 'CONTACT' => string 'aaaaaaaaaaa' (length=11)
Where are attributes?

**Comment by dkrnl** [comment]
Hi, can you write full(working) code example?

**Comment by standus** [comment]
It very simple: use this example:
<?xml version="1.0" encoding="UTF-8"?>
<ITEMS update="2016-11-30T02:53:36" version="2.5.5" >
<ITEM uid="1111122222333555" count="1" change="2016-11-29T03:03:37" how="1" author="1">
		<CONTACT firstname="AAA" lastname="BBB" phone="111 222 333" email="test@email.com">AAABBBCCC</CONTACT>
	</ITEM>
</ITEMS>
And check if you have parsed attributes and inner content.

**Comment by dkrnl** [comment]
Sorry, but thus example not working code.

**Comment by standus** [comment]
OK, create any own example where in identical node are attributes and content.

**Comment by standus** [comment]
Did you closed it without test? Hmmm.

**Comment by dkrnl** [comment]
It very simple, write another issue with working code.
