### ISSUE TITLE
XMLReader::read(): Load Data before trying to read in /var/www/main_lib/XML/SimpleXMLReader.php on line 114

### ISSUE THREAD

**Issue by Micle86** [dkrnl/SimpleXMLReader#7]
Запустил ваш пример: во первых он не работает в пространстве имен, пришлось все XMLReader заменить на \XMLReader, Exception заменить на \Exception
а вот что это за ошибка вообще не врубаюсь

**Comment by Micle86** [comment]
также добавлю что копировал файл без композера

**Comment by Micle86** [comment]
также проверял 
`$file = "example1.xml";
	$reader = new ExampleXmlReader1();

	libxml_clear_errors();
	libxml_use_internal_errors(true);

	$reader->open($file);
	$reader->parse();
	$arrayErrors = libxml_get_errors();
	$reader->close();
	$xml_errors = "";
	foreach ($arrayErrors as $xmlError) $xml_errors .= $xmlError->message;
		if ($xml_errors != "") {
		echo "XML not valid: ".$xml_errors;
	}`
ошибка таже

**Comment by dkrnl** [comment]
как воспроизвести? мне лень разбираться без рабочих примеров.
