### ISSUE TITLE
Как достать значение, если используется CDATA?

### ISSUE THREAD

**Issue by Xomiak** [dkrnl/SimpleXMLReader#8]
Делаю парсинг товаров... В поле описания используется CData:
`<description><![CDATA[Комфортное и ультрамодное платье в крупную клетку Тиват &amp;ndash; идеальное решение на каждый день для ценительниц всегда актуальной классики в современном исполнении]]></description>`
	
Уже что только не пробовал, но результат получается таков:
`["description"]=>
  object(SimpleXMLElement)#84 (0) {
  }`

Как достать текст в таком случае, подскажите, пожалуйста!

**Comment by dkrnl** [comment]
$descrittion = trim((strval)$nodevar->description);
http://stackoverflow.com/questions/2970602/php-how-to-handle-cdata-with-simplexmlelement

**Comment by wiistriker** [comment]
@dkrnl что если в https://github.com/dkrnl/SimpleXMLReader/blob/master/library/SimpleXMLReader.php#L258
вместо 
`return simplexml_import_dom($node, $className);`

использовать

`return simplexml_load_string($document->saveXML(), 'SimpleXMLElement', LIBXML_NOCDATA | LIBXML_NOBLANKS);`

Будут какие-то побочные эффекты?

**Comment by dkrnl** [comment]
@wiistriker -- не думаю.
